"""Per-factor economic / behavioural rationale, generated by the reasoner.

CRITICAL contract: the LLM is told to use only the numbers provided to it
and not to invent anything. The synthesised text is a hypothesis grounded
in the statistics, not a numeric finding.

The numbers are still computed by Python in `src/research/`; this module
just narrates them.
"""
from __future__ import annotations

import json

from src.llm.deepseek_client import safe_reason

SYSTEM = (
    "You are a quantitative researcher specializing in crypto market "
    "microstructure and behavioral finance. You explain WHY a factor has "
    "predictive power, grounded ONLY in the empirical statistics provided. "
    "NEVER invent numbers. If a statistic is not provided, do not state it. "
    "Be concise and rigorous."
)

USER_TMPL = """Factor: {name}
Definition: {definition}
Empirical results (do not alter these numbers):
- Overall Rank-IC: {ic}
- IR: {ir}
- t-stat: {t_stat}
- FDR significant: {fdr}
- Regime breakdown: {regime_ic}

Data source: CoinMarketCap PROPRIETARY Fear & Greed index (distinct from
Alternative.me), plus CMC global metrics (BTC dominance).

Write 2-3 sentences explaining the economic / behavioral rationale for this
factor's predictive power, and identify which regime it works best in based
on the regime breakdown. Frame it as a research hypothesis grounded in the
data."""


def synthesize(factor_name: str, definition: str, stats: dict) -> str:
    """Produce a short hypothesis-style explanation for one factor.

    Parameters
    ----------
    factor_name : str
        Identifier used in `research_results.json` (e.g. "fg_extreme_rev").
    definition : str
        Plain-English description of the factor (from DEFINITIONS map).
    stats : dict
        The per-factor block from `research_results.json`. Only the keys
        listed in USER_TMPL are used.

    Returns
    -------
    str — the LLM's narrative (already logged to outputs/llm_logs).
    """
    user = USER_TMPL.format(
        name=factor_name,
        definition=definition,
        ic=stats.get("ic_overall"),
        ir=stats.get("ir"),
        t_stat=stats.get("t_stat"),
        fdr=stats.get("fdr_significant"),
        regime_ic=json.dumps(stats.get("regime_ic", [])[:5], default=float),
    )
    text = safe_reason(SYSTEM, user, tag=f"synth_{factor_name}")
    if text:
        return text
    # Deterministic fallback when DeepSeek is unavailable (402 / network).
    # The numbers are still 100% Python-computed — this template only
    # narrates them.
    top_regime = max(
        stats.get("regime_ic", []) or [{}],
        key=lambda r: abs(r.get("ic") or 0.0),
        default={},
    )
    return (
        f"Factor `{factor_name}` ({definition}). "
        f"Pooled Rank-IC = {stats.get('ic_overall'):.4f} (IR "
        f"{stats.get('ir'):.3f}, t-stat {stats.get('t_stat'):.2f}); "
        f"strongest regime-conditional signal in "
        f"`{top_regime.get('regime', 'n/a')}` with IC "
        f"{top_regime.get('ic', 0):.3f} (n={top_regime.get('n', 0)}). "
        "LLM rationale unavailable (offline / quota); numbers stand on "
        "their own."
    )
